module.exports = {
    responseMessage: {
        COMPANY_CREATED_SUCCESSFULLY:"Company created successfully",
        EMAIL_ALREADY_IN_USE:"Sorry this email already in use",
        INVALID_LOGIN_OR_PASSWORD:"Invalid login or password",
        SOMETHING_WENT_WRONG:"Something went wrong",
        COMPANY_CREATED_SUCCESSFULLY:"Company created successfully",
        LOGIN_SUCCESSFULLY:"Login successfully",
        UNABLE_TO_FIND_THE_COMPANY:"Sorry unable to find this company",
        PLEASE_UPLOAD_THE_IMAGE:"Please upload an image",
        CLIENT_CREATED_SUCCESSFULLY:"Client created successfully",
        PROGRAM_CARE_CREATED_SUCCESSFULLY:"Program Care created successfully",
        UNABLE_TO_CREATE_THE_COMPANY:"Sorry unable to create the company",
        NO_DATA_FOUND:"No data found",
        CARER_CREATED_SUCCESSFULLY:"Carer created successfully",
        PASSWORD_RESET_SUCCESSFULLY:"Password reset successfully",
        INVALID_PASSWORD:"Invalid password",
        COMPANY_NOT_FOUND:"Sorry company not found",
        CARER_NOT_FOUND:"Sorry carer not found",
        VIDEO_NOT_FOUND:"Sorry video not found",
        CARER_UPDATED_SUCCESSFULLY:"Carer updated successfully",
        VIDEO_UPDATED_SUCCESSFULLY:"Video updated successfully",
        CARER_DELETED_SUCCESSFULLY:"Carer deleted successfully",
        VIDEO_DELETED_SUCCESSFULLY:"Video deleted successfully",
        CARER_LOGIN_SUCCESSFULLY:"Carer login successfully",
        UNABLE_TO_FIND_THE_CARER:"Sorry unable to find the carer",
        CLIENT_NOT_FOUND:"Client not found",
        POC_NOT_FOUND:"Program Of Care not found",
        CLIENT_UPDATED_SUCCESSFULLY:"Client updated successfully",
        POC_UPDATED_SUCCESSFULLY:"Program Of Care updated successfully",
        CLIENT_DELETED_SUCCESSFULLY:"Client deleted successfully",
        VIDEO_FOUND:"Videos retrieved successfully",
        PLEASE_UPLOAD_THE_VIDEO:"Please upload an video",
        NO_VIDEOS_FOUND:"No videos found",
        POC_FOUND:"program of care retrived successfully",
        VIDEOS_UPLOADED_SUCCESSFULLY:"Video uploaded successfully",
        VIDEO_COUNT_UPDATED_SUCCESSFULLY:"Video count updated successfully",
        PROGRAM_CARE_RETRIVED_SUCCESSFULLY:"Program Care retrived successfully",
    }
};
